/*
 * @lc app=leetcode.cn id=459 lang=java
 * @lcpr version=30204
 *
 * [459] 重复的子字符串
 *
 * https://leetcode.cn/problems/repeated-substring-pattern/description/
 *
 * algorithms
 * Easy (51.64%)
 * Likes:    1186
 * Dislikes: 0
 * Total Accepted:    270K
 * Total Submissions: 522.7K
 * Testcase Example:  '"abab"'
 *
 * 给定一个非空的字符串 s ，检查是否可以通过由它的一个子串重复多次构成。
 * 
 * 
 * 
 * 示例 1:
 * 
 * 输入: s = "abab"
 * 输出: true
 * 解释: 可由子串 "ab" 重复两次构成。
 * 
 * 
 * 示例 2:
 * 
 * 输入: s = "aba"
 * 输出: false
 * 
 * 
 * 示例 3:
 * 
 * 输入: s = "abcabcabcabc"
 * 输出: true
 * 解释: 可由子串 "abc" 重复四次构成。 (或子串 "abcabc" 重复两次构成。)
 * 
 * 
 * 
 * 
 * 提示：
 * 
 * 
 * 
 * 
 * 1 <= s.length <= 10^4
 * s 由小写英文字母组成
 * 
 * 
 */


// @lcpr-template-start

// @lcpr-template-end
// @lc code=start
class Solution {
    public boolean repeatedSubstringPattern(String s) {
        int j = 0;
        int[] next = new int[s.length()];
        next[0] = 0;
        for (int i = 1; i < next.length; i++) {
            while (j > 0 && s.charAt(i) != s.charAt(j)) {
                j = next[j-1];
            }
            if (s.charAt(i) == s.charAt(j)) {
                j++;
            }
            next[i] = j;
        }
        return next[s.length() - 1] > 0 && s.length() % (s.length() - next[s.length() - 1]) == 0;
    }
}
// @lc code=end



/*
// @lcpr case=start
// "abab"\n
// @lcpr case=end

// @lcpr case=start
// "aba"\n
// @lcpr case=end

// @lcpr case=start
// "abababab"\n
// @lcpr case=end

// @lcpr case=start
// "abcabcabcabc"\n
// @lcpr case=end

// @lcpr case=start
// "aabaaba"\n
// @lcpr case=end

// @lcpr case=start
// "xkmjusbyzqmvtevwpmthhrfzdazynvnxddhcxnjkjqdfrauwcjqwnqlysaflwpxlpmyswsiwrrzynpmrkzumclbactekxovxlarnvcnhoqqvuijwedthfdqbxamvtaoaralzaloqpgtwyfykvfvtrbqifxotohowqgilnimfxmgctxpiadtwozvwsmwwmqcglqxhifppssnrirwobfuppvdvyndcgkgymzmzdgsgvyvikgtfftachuzoiqpvtkmzbcdrbvxrwrzzrsjkaheeufwtsmunyczvyuktyoczcpugjncdatlzcdrkmstrzzqsagyhnckmozxizmmguqmsepnjahmtdjhayvdasyhyytxsyfxghaqeddbirmhofyxzbsusfgghuhfuryrixgibqnjdkiskurwvgnxczuyxrncjjemfalyupqsqncidzynjozzbrpdecmnmkalxtahrrrtaricvxnvzlkgbtrubbqfdxsotzdadqifxrjwxlbocksoxkzclqopxtanwdckutdardcmczjcgfrqtzsrejlaojqgbdudkpdbhpppmkbufzpecxkhupbrfsrueafwnlykjkimuimlivqiocximjfmqvbadbshzykftfajcgjrxwsfrxfniyvphfchxvvhzqwqhhuznwskduiffmmctaamdwlwtitsyremdxxxcuwupudozqbjqatqpjiznaaopcqdiacxbzcgtuajxskqmgernumigtkuaprciqdrpkjghjijkmrzdnnlkxlpuuzbdzwzpocncwizjmvvnbkofgndrewdkjinjgewxhgpfugdcyehsyeefgtuvgwvjrjtwadfwxvoihggelmyltnbnopjxojgsakopntiknhgzwkeafipguowkoxfydkprhmnjrmilnwwpnrtcjdtvgydliomxulcmfgjoppecsqbtdyhebxhuuatpufmgxomqooapksgoflsvsxmzwcaobegpwoclwtvirunfvsoeuwvgkjyyjhprechvpzpmodzywgzebagambtrunnzgphdpfsbasjftdlfrdjmqagjykhiqpmhntzmpyszrtqzablkvaojjczdfiwbhxhiettmcpkmsvqvcbrcfmksctxzmlcrmlqqaffsbnnykxbevzgzksbnvpenhiqhvnpqosgftbvqzyxkbbaubtmphfpqbzdbstksmoqfrarssmvkejtugdlgvfwdkmyygxivcvqefovxffeahhercrvnqwzbnhljyghfpdghwpsepnlgzyoguryfbjtdujwhuqgnnpltktivudedotackybqmjaqeyvltugstkbpfyyhpcvrumcoyjjubajdffbvkhgzxzjjnfvsxkpijgtuomyvsvofxvjieeydghwaecobeyanyviamvadugkynmyplglbytgprxyirlkyljfedpzxdpqwfqwoqqgvzpyngnhjivpxygylpbdzldgowtdfwhsntwhiqxgyeupgtwzeryyayyijoslpxdkdbcvnebssentbsbjyyisvzkcpgvvrfbvctakeqjoagpryiomvvyoelxwlmtzglgnwuugiaygkemtlfcfrlwedclfuzapfaygzoxsojomopavsenttulxwytlkathrbcffstlcqdtxvxopdpcynqrdxxkovfmggmrivmismrvfxxgpnmfwljaqvxswvddmhifxbglawvpvlwngdxdcjlzskcftyjgdftlrscydmkhuxumipwhayqmzgfkutvpmtrkiyfoujuvhuitfyqveotmcsogvqecsvmypbdmhixhkoxoxkchfasqqxnlpvywovrsmczddtehlhgohkxkrjqkxoiizktkdnvrafylmewszyjxcafpkuwlpumbtyduuosbrkwxcjtllcbabixjcrkjggscvathtpfvnkggmrmpggotxwldnutuumlluzydmjsdjxkhhleqgnscwmcomeumvxelzmeviilvhhpfvcpiglojvedlekxzkpfwfhsxkkdxaxejhsogdrmswsqzzknjmyofqyizhfzhsvvfjrgevckxohrzibmmfgkfkstyfxgpkzakrdpjmwfzqkgxqozsxuvlzebmfpopfftwmmtuceuenqkwqxccsucxefmxbsynvqpxbxsgkzzpyzzsfpyxprgjkqasqomtiecorwtzgbowpyeforenkynnlxvirkdqheqscagercihvhhfprlrghjgaewericdvstgozaoxzhvzsxjrvwcdxfsriczsqubkpzhdlxsuyyckwptrriyeniypjdjrongpquetrfvusnahwlvslrgdizvkfkatwbfrxkeyvlkrsrhqyjzjebaszrkypxqhotlyafvqjqegeorcmwqqotxtjiptxzfkvopzrxejevcaksnvbpjufdgdrcxmlwlieldommatbwpedhlvkpeaxoknsuksekjlfnzlbsgfjumqxngxoulmhvxtrkezgbqzatdoegqqxxctbnbbxcmpbvzzalzklsbhvxsyarjzakxjgbdrmtgwftjjxtorxdqsgljmarshuoejfrjamcpoxbmqyskdarjrprhevccfwintwsjjpjlecgylpurxfgpxodoppemciodpziunmdkeqyakzxpnkdsatdfaukoxiagdcrzdjjlfarxxhwxnfgsfrldtgcjjdhraewyaugwvgxarlbnhvcdpbngnorecvmcvadmzxmajenvenehpktnwcocazbzmwdbjctkoqlngoyjjdaqfzohniuxspobnlaqegyilziigrmmahjghxefrxgyxwzomwimxdihhuijfzpkojdzkmngstojffvnoqaqmllphycofjblnfezpegiepznfnuycsziulsbqyxhxqaronctcahbaapvfmbokiixkqwaiykbbeucshdvegrqdjtfimcieeegqjsecvfdgvdkjzliptflgumrjfldodtfqjpnpgvyfltbbgmncvhkiruncmpuaiyhucthfdjabmeqdeoaaooodpdwrtmixxwyeyjwnywrrncfvrdqflyscliwwnbzsztqwkcddmirkforoqsoyzfwwjuaolismetkualisnlvdmgffxmbqaocqwmdguwemtfyrqvdmbuccqqtynbadpapdkpogsomqfpdqqhfmgwcuvdlknnkhynkqajxrxlzdcabsiqvcykbvjhgdwxvmjkubcntwlilxvvakyrnjiuucwsuxvhlmbsaxuotjoitkmngxpkpldtnhrxjqrfsgqtxoxykftsyvqowucbyhatdujsqlinptxoyfkgygqhwzpsgaycmmmmlsecjmtsjpnbsuxxaaxxkxayfzhpiscijaxfhfaxjwouerzcvevikejsefzkxfglrgovnsbtuwihccceorwkcfuggaysbklgbyqtxqognibxclpukgfbuzuhkzzemuprtgcoesycpwjkpayewbwdmctsjivxmmpaghurgoxbefvniinyaqbhszxrhfvztnjcdgjocwoliscvwzbvpouhcfsjoqnybzszumkqarplgcsrqvbqbjnyhaojfzglmqsfuaytaaadfxxsopihvmbnchrkccpnowozrugvzzcpqqbvhcrmlazflovnixyumozssjcnpezmkfvuovprsrfpzckzdyktlarvioyhztpakmdqhqndydasgcvhjvwqamqrqmuswieajrzqmyigpvtkvhrbkwjdziarttbvhqwmgfnpuefsewkovrefecqtfqugicnxaghglhcpnxqfpjoskaigokiirpbtpdbzfrjzguojlpqphqpmamvrpzpwagqivzttjdltyftaslevbfwxouwjurkrbmezfqdznivfgqrliinhrvtncogqkzwcxchhhjmqgeuqrjezwmtrfztzbozpigtkfrbzzrbssejmbnxzxzqisviokofkvhvtjdcvixuzlieindmmhfrxtokmouzpmtpgdkffkoeelklkdjcnuyalyoxyyogjacsjfwlizsspeanicuwxtunplocqxmxfdofazbkaalqqhziuwjuzprhpqmfoqtnxnjsprtxsqidivvbtdfjmbjsvnhetvqjaelzrhdjpgitpimwmuqpwzfnynptjuxjadotnkonyhxbeyxbkshxmhmcjmjcnfwlhwcykrifanadtqctlhfegytcsxxmbivlygozrfrygaljniekeeuzmvbnjkwttevyywknwneuhxfwwrohchwcptpqkefougsirugnriazkwozhvaanjhyrpughqhorenqrgvmkksvqhjkripmkmjbsdtfsxqukivqdumyynogfxlxvhzfxdyijlvglvwmksjfqntiazwzjiygnactcrarhdqqqrgnkaorfswojmjfefjzdzossmjqprllsvlnoklknzukscsqvxbhqzlfbxowlvsqaflqexjfhlmlthouhsvfataineuujcbovldvoceljfpvgdyanxextucrcytyyjwcefdcblbozbvmdbiuyvdphymgsdpncnfhfmifhgpvvvddexeabhejnikxrabrdnfxfdcyfrvqxpxmywgmmjuduwutzemcmqbudnszaaarlqoahjbrrvdlwvxppcdzxrqmhznpcjkljxdyltcjlihcwxepiwfgdjvycoamcqkcmjqihlmilvcbnovrgfaqgbqcprrmhijyismbcgfkjzoawkupuillmikukfohfjrapsaecmfxvvcpsiosjbqpgtyztdxzvbzadxlprtvzzhldvyiamqkrjnybxxgnnbcilyijqmfcgjbtmeobfaxsquqjddhqpjzuziqjsyyrluipjszmrzqreoppytxzzvnbgiooijyyquokjtcedrastformrhqarhsauobahllbwcwqqqwohauasevptmxopqebibashpmheilaefqadjovcldbgdqtptragscaxnluujbjydfnqxjlvtdtflebmswhkmhylkyyaltijcuzgaclztrknfbqwpqujcpvnuulxlpjcblaertebbtkbrhkxxgqbctcmfcdsxakipjpyuuhumuvzqudhiataoehozmpelgpdujsnxejafhquzqtpznvkgibsnolvqozrnebtaatstjqjdiusynfwxbgfuqkzovhudbdywbazsdfizcyikeoxygadopyphttjkklxeslixmrrigplsbrrlzpfvtxiecqyecqajszhzsgeykcmrmwfnbjjwqevwclxdbwfuaotbjavkfktyaclteynccofcsgmqemkuwlsqwpjrbsgmjbddemafrevxdpkehbidbbugwsggqmbyeecpawsqsmdvxqocfziyamascxfmgzvmhqlnnjzgzxbnsvhgxuxmhsclpknaattrbaobcgaoprgkeedpbddjhtxhiuphhtwvqdzabvttnhhrzfjlylcsqdqsjwjqsqfqkbpbjgljuwuxoiqorksrrdpehjkqyqqiurhdnfeobkoclvpbmhnchcvovxbwsekmnvgmnywksuafvkbmbxnxkdputgauavkjfhoyymmmbkghkpwgrtzndmmbtqvgtykimatlanrhgfapgwgodfpnkvwtuesdmditncttytrdqsfymuzewhiomeeytwpdjrqqdiqikkwaxpbuxludlsgdvwqeyhcrvncdpghkjycsjxvaoykqtlwexdokkvvckaaxgtqglukictsorssexcibxiakuukoijzwpvltaetpzmxaxxzpnrxrutbnguslsyrrlzqfgrsrwbhpoxfvystlsatvzvhfbqhfplrrdcnhrwwjcfgeqgofejrxcpkiczogdmetofgqrbvihewrilzerxakjfewkngxwkanjxdpdfhotsmtvyelegiwkgseiqzeibkpxvaawefxylptniursxudupypyhvpyujfscgbzkmoyirlokrohdnqvzzvzjywyihsojciahptwnebwlzvabnbhuqtvilnhjgqewewkxtxiguvpbirbbqkugrjdnjjseptmsdghnvbmxpofgwtgdywkobcngiadyuwuccgdlgoscjvcryhhhpzchrhqwkeqgazszncxezxhbwttbzajnjgljdkhtwbdumzbvpfpgoszqkfeowoduxgypfgpcnhuzbsuhqweqpzniuwujlwotewtplzapsyjcbjivbnutuyovbwyqvasfdwqiihlbgypvqvifdmmmbzfpqrsjkzmqklieonctvsxcziyfiefnuqqhjxcdikwdoatdglhdderjkkmmctnykdndvqwhpxzbvyyikihrexwurhnnazdbxrgmjxaeukaeumtzyojfpehkupbmwxzzxlkzbpfgyflngzuuacsqldglucyuecstwgopmkirbuogctmzqhselchlwkgymxhhpkwcnazcmzrvbuagchgxlhcujkbwtcjxtvocmrdpjumaprmftriikbecuhftsdqjpamydefzadenxljfnchnnshhvsvaihfnanxtxiumjudpeheutvayrnoaclomdebhqbmedjfxxomsadzvjrfuhmgmszpfcahtzbibwdeqdxanqpkqzlqosoiljxkpzluhmogwkqhckccxwyqhxjslmpdcxcpnkixsqrqpyjrrmmlxrtkcqgsfwrajkfbrsomowhwzqadyulokduojcchszdojvkjscxdeljostagvelawosbgfzzzefnvlcgpmrhoiypyylduuknxqsjanuqeaguruhnvvwjhrhdsdmgrzgmwwhcrndluycdolmdltoccypwviunqqrhkoclrrdpjglhntrkamdltinbmdqvfvrcmakxtcjykzmtpbadvzywecjsdvcdhiveacfyszfekovgbxrdsjbkhbhyfgzncnzaizbflqnrtruuojaiboaktrecnfkdhiqrdcigojwczqqzqquklzmehwxquovvxpxrcqjfnflptdjeiroekdlrwsiuesqjuuxkiyskriiseqcrrxtfiotsijvpmdmupuhjzxityknwitlcklyffnjifcscbjfbdvieappjjfvwakughujjaimenqxyebofbzbqjndlustljadlkaptqaydyrtdffrvcvpbmzsntohttmktpsaiykaqktobpinlreqmiorhbooaiuavurejqcklbludcbayhctrndyfzkwutfioszteecnqtjwzisxcxbqhfuhbrgikbepbcxfibbxllqwsmtdveaighrpgnrkbilzindsjklsvlhpbvdcsfehijkayeemfublnshkwjxgmuklonzqegsdwtehxrfzlewlkiwtmihjmqppfsuaasfmwaybhuqilynllbftognjofdtbdexyezptiknhiorqcgpuzusftfjqrntsuidnukdqnjrombvuexuzszwwprzrlrkmezrfibklwmdfzacverytndsfrkwanqrimyhrxnghridxjvvbwmleylmtffmyfkddlfteacuahxdsvfuzjkreyzbuzazsdzrlpoavepgfwajvgdqitorzpchfvldcirdyiwjpqdknqtbocwqtrldypmlpxgzccilamhnselmnijphwighutnjgyjtcueqkivjrhwzgbjgqykclslpicsdbyamvbujfinwuiuheocuuprqtqszxferkwpapqlaeopoqxyggutokmuhmdnuapbajcdqdacaudlqbpzlnhlwikqdeuzojldccvovabqkeanwctmpptogudwglhodezelfsgsxjrqbbqxkdygcsgmhfvofxsufuprnhgsnhxzlpxzlxhilsymmwkdyemsiquznxhubgykbzgetxudbnauohsxyatqqaydxrrenarpzwqvtsctvgcrbnijpvclesyrqyfhxzqudaytyzdngvaqskylaqsspdfsbyxtpsuhtmkytlhcgppmmijggaervjitbtuiwmtkkcpilvuuypzbxwmgpzfdakvaysrfxokhdhrfxgoybusiavkaqijtotgtguisrhqcecggwrznfnajmgyiadmbanuldddgtakcrzbyhwinqdetefdiflesxnmhujywxhdyowzqrmgeuyskcdbhjyxngjrguoslcweswcgbxexlbtukuuvenrvsokkxjqydqlevrtpyvpyzqswgslopvmjckrhepptoafxcbsbymgwfstwqxxmuiceoayarlihhzlucykshjsgsysubxnwenittlkhjktemikzvbvvelxjehmqznmmnogjampvbfgdvkdjcbacgeigseiqbojbjfhoulgdgsgxbhdomevbgoxrqhthpbqndvxnlbguepepmlhptbxiyllbvbdqcpnqhpssojyufniezblbkbukzzpcearejpjrfzzkxjajmuorutnuejimlgybagywkoiibswdzejdwmqrvznufcylrsbdcafeeldoqowdeeheekyhopgfcqcveiuoabwrghfnwzbdorsxdkmlzeeikojefxcsisybsvgxkgooibuntrgshqifywdqsyjqzvrokoplfchlqegrlzwearppuurzmkejnyciyecovrsdsvpoytxveabxfruvpmbfivswsjtrhciiasusjbnwyvdvrguvyjogfvuluuvapnhqigxpnnrlwrbcmbvpmomzsqogpgjmvlsuawkkooacxxrpzpthctmzepjfbwtribegcjcccyevwvorzhgvvsfvqjozwrotpjsnqfbyrsvuuvtgjojrqkwrjmllpuseffwrpzypjdfcnhjtqdzrryjioaesnrykmfjopjmudndftcxfioqlocfocgkyabsqgskfxcvftfkznslbykijhpgekucvncctgtmcxocxgfyabiorqkdstdfervuqhqyviysrjqqdsoxfdlixtpxecpqewwewshaqrjjsczlirzrbdmkxfczydrtmxbjvnfpamcqfsyeslljrvvxpolnandnxawxjgauzebugikvpseyibzhhjyajdkrvzztoyuejskxeuoicmoovsnkwgfiaimppbqndbxrxecthkydpujfsjsffloryrxcpopyuudtlokknemyxcxlcspjfthtrgifqacjm"\n
// @lcpr case=end

 */

